require_relative 'tests/geometric_base_test'
require_relative 'tests/square_test'
require_relative 'tests/circle_test'
require_relative 'tests/triangle_rectangle_test'
require_relative 'tests/rectangle_test'
